apiVersion: v1
kind: Secret
metadata:
    name: giantswarm-oauth
    namespace: tekton-pipelines
    labels:
        app: giantswarm
    annotations:
        github-url: https://github.com/organizations/giantswarm/settings/applications/2097020
type: Opaque
data:
    client_id: ENC[AES256_GCM,data:dTtNUA+k/t1Vw1tTFVMLbLPjby8/gYFdu5zdSw==,iv:etw9R9csj4LdAqOyrEVvMSJNGjgpgTULiXkGQ5F5WCg=,tag:0jJLmHvhgRYOy6nT0HcX+A==,type:str]
    client_secret: ENC[AES256_GCM,data:TQ20HrMK+sNz6ntBRD4Ee24a7MkcrqE08bsCFyVb6elLnZA55i8Z0Ct5jvGo8Sy08cLUtI1UHR4=,iv:DkAAfCgWmNSuQMQU0uAk9Fd5HFxZZOoNabZu/Qt4yR0=,tag:m+8LPc4llHA9/vuRwscZAg==,type:str]
    cookie_secret: ENC[AES256_GCM,data:8pMPj/xUImGn+It5RiOiSMxsCXkl5GCKLHs+Te8egBbIjx3H2U6V4idRdGo=,iv:yjCAWYnBwZKhN32+gIJynTHIwh5Z2qwgVJFIBKe9js8=,tag:PwgM7YcwPCW3zZcT6q0LcA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12vs3x7x0ne8ghx4js9dwetn29vvtrrelvcgup2reqmdhdeqwd9hqht25ex
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3ZEhZaHRFWXhZQU1HU0t0
            UEtLN0xJaGhjQy9xZThYQzhOMHBwdDJaV1RVCmxwNHBXbjZwem1CL3VJcXZoRTQ4
            dk9BZ01SSzBGUElZcW5PYlkrUzNYRDAKLS0tICs4NGxaU1U0SVRNYS9iZW5BM3V2
            cGRUTEJGNWRteENWUlFLbkI2Z0dwVTgK3MI/v3sJBIwQ3ruVR7YgJr7nXoc9hGcJ
            bNZfOOw8rU+hvKUqxrVWQS9SGalL65lK7znEvXhMr0zQwPl+CViDIA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-31T11:55:22Z"
    mac: ENC[AES256_GCM,data:OUOYVWOJGQw5y6DU7pIkVu+0ecofKmG/nDhyPdY56mPJlwzXmHt4bO/cOtR61E2t8cw2LwpDlIfebHQB5rN/qTngSsKDWPwvi/S08kwX5CQsSJ0tz8laQaFb+4l87nHaRF1AeQoDmhK/Nkm00g2pAsbW8PBe4gx2vhYDnnDMvqI=,iv:ciTev4fxJUp4ft5GQ5g9mHzoLgo3Hk5yO9sGVki6dEs=,tag:IAp42nwOn0Ss9kohCLkGRQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: regcred
    namespace: tekton-pipelines
    annotations:
        registry: quay.io
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:IHbauPH37tEDg8GRU5SI3N1C1LvGVEBclrBIr3H9Cz2uC5x6i5Yr21sUTtEc5/QU20I9spVZflXLLYWBszdy35IU99W7lSkheQQQwxVX+IifCL3K3DHT6reLLobeFAQT0Lfyg8vG6iox5Kobc/rPCoyGBPkSbNLmAfNWVvkFZ/835gmQYDPEimk1/ZFgZWesNtUXN8va1P81hpYEj2OmbvrhQJFgI5BKcNkHZacwN/kfGxD80cghaak51Fk637tOcyhQk0ztQ6+64fsIVLljEgrVT1h6XPnACrQFznlDpK9kIINyxSFfWq6P1DZH/Rv0bcVgHA71xY2BdT4HMLY30MIMCnOL9wgnW3F2cw==,iv:sL0WopH+TEVNffzIwAusA3Hsdq+VR2Zuc5O9+55Vk64=,tag:tqlSKjeyODhibjFH/CSSIg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12vs3x7x0ne8ghx4js9dwetn29vvtrrelvcgup2reqmdhdeqwd9hqht25ex
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3ZEhZaHRFWXhZQU1HU0t0
            UEtLN0xJaGhjQy9xZThYQzhOMHBwdDJaV1RVCmxwNHBXbjZwem1CL3VJcXZoRTQ4
            dk9BZ01SSzBGUElZcW5PYlkrUzNYRDAKLS0tICs4NGxaU1U0SVRNYS9iZW5BM3V2
            cGRUTEJGNWRteENWUlFLbkI2Z0dwVTgK3MI/v3sJBIwQ3ruVR7YgJr7nXoc9hGcJ
            bNZfOOw8rU+hvKUqxrVWQS9SGalL65lK7znEvXhMr0zQwPl+CViDIA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-31T11:55:22Z"
    mac: ENC[AES256_GCM,data:OUOYVWOJGQw5y6DU7pIkVu+0ecofKmG/nDhyPdY56mPJlwzXmHt4bO/cOtR61E2t8cw2LwpDlIfebHQB5rN/qTngSsKDWPwvi/S08kwX5CQsSJ0tz8laQaFb+4l87nHaRF1AeQoDmhK/Nkm00g2pAsbW8PBe4gx2vhYDnnDMvqI=,iv:ciTev4fxJUp4ft5GQ5g9mHzoLgo3Hk5yO9sGVki6dEs=,tag:IAp42nwOn0Ss9kohCLkGRQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: tinkerers-ci-pem
    namespace: tekton-pipelines
type: Opaque
data:
    GITHUB_PEM: ENC[AES256_GCM,data:WP1m9FfkdZV0w1kqdyPWb51n0Tq0XElxGZWUJmLsAXj4pw5K6ScFsYDlm1qVfO2LGoevNCyiPGBFKUZdhqdmk4a15f1aCb17rvDpmwAPSEUhhIi9FVoN/WIMQdr5aSy8CdCdBVIhfqQ1yiCV/MRbsUxx6WsXovm3l1Zc/57ZQb3pRzyek2ifcXXzz1SM463y/KKydlCsJrjRDNnGo5QvZjPWoPlg5JVDnvdOAMRSRX/vpCOTX19ImWlHBmFeLDeqRFXAcaGarsAJcB1IuZ9opAzfgPL8H16mLaIlmZbM54U6Ah5MU1WFv3Zm4sY/KhIuw3G5WCOj2B4VfY8Na80q1KlbBPcgQlnltOrlQ8d1raOCs0s4SSXtxDqr93sbbsc/C+OhERdfAqgxLgLh8mVm0blKcg+3pD1oWqvpu6Aq1EPtEqwMXMgMpu9RM5Gfuf+thQZSqoKfL4CSmyLF9kt+QL/uqv4oCkdYQtGFUi2GEbCneabT3B4lAdYVZun9c7lt6ZpfmUawdA9sOhs2gli1vUj18RNw5swed4qbYmpaIXUFcJ/aIzoStB/zjCVB380FlBpcO1QQn+ykh9qheM5LQ48EFjpkbC+EVtwp5HAyODVC1vjKhheYEW/fYRo2XywvU9C1ZhQwqm+pdciHzcH0ZCuRrL8zmwiFQz8vs+jXA1FWMva2PvnPjk8WXOZB6ipBXXcFJNYvxscqGa+PU0x95ViWGpEx2Da3XDAFeMh9qY/Q6qoF0ojAeHEXLRoxxRDkfwxqVjPE1oJIOayypPV9nfQwMeAjz2FAIkH22fIFFMP86lHwK3szIyWBOfELYer1C54WdtOi8EMZvK0FN1I4HP3iGdhkOksjYHc8uoBoH9IrtN4Nn9EPSPOnmIdoI//9pxj6cBi2C6x/Wyh2lgbdR75V6/ejsYCJdchU7bnm6Shs2wDOj3bNmmZKwl5XWqZNazttTjs0o7F9gVera1FLA/uT+ZGrCKPafp6DLMTX33fEkU2XlY7vF4b/sMCmlDVAhCcnMBVU8opV4FryU3qxhHs/CDr1hqAkKuTLvY2s/VPKgkloVrUycooHYyuiaisZ2ZgWg6xG5IexWMZ5T7P7yIAh8+u0+mxy4sTOWgdIjzwa2BMwzn/o+HJHTqhAZBXl61LWuKURNmlaPF5jJR3m7BohbX61/sV+eLc49UjylEmQw/DD3LpkHtw6TBg4o0WES1dHh0yZG9t14EDmi3S95KrZQMa7vd6ctBv2LYKQ51jbaGjy9oUqIPA/DCS5qcYqtgROmpavHkEEqhN+B8cexkRymNPEl+/5uVhJqUVmDE2M46mIrTTnUQxGwz21RXQzwKjiNIifAtWAlGLGZGATYNamV9g0hQNZV9hAEbdocLWaqM3sinlp1jj+5YEVu9Ljaa0Op/kn1fFGvFr2hF5rFZGo1Gmz+cQk/owpUPavvwapjnV6kS2gLvk4vVEzfl4FKfpyhmcO9+D5JJyMe7DX3/sfUZQal58mTypoKydJtSi4B4uGSYFFbsHKZ7P6OPxcMESvCa33MvdKiZfO+oUr6dgbAQO1btzdBzVB8iiSORxyDvcV9OlmYOrqQeDQWKOVd/vMY2pJO4stdOFwNZofkvFl9eQ1CKZCjkX69KytAaL1oDKL4/RNX8IvKecZLFTrIW99qu6yV/B847PPHxoGB9YaM+2HazUSODU2QmuQ6AdljKrU7jrF83D7uuprD+/czC2t4VdP8LeProiB114iPiewsUFX4tlo5aPOk+Kc4QNlTtUw5yK3w5mhn02ApA+WnDqf+rBUUeqGApGjUxqyciz9VqZhpTAi/FY4dFOZV7mqWkIvP/PJXmUyhbKn06ff8Qc16FpRQan0Sp+EZxI1b7wsUKTUA9uViRkVuvsFxg8HY9bdCJpDo3R2xPCuOg7725MRB8+Kwu22c6uW/yMzWzG5V90hyfFEAFYbbB7ctSbqzvk+TMU1ZNJCIRrpNum80USBXtARrkCRsmoH1kA1ATqSa3zhv333U4wwCQU7so5b4kAB/O5rn6gxbcJL+aiB3dhM7BBFI7ZJSYBzyDFhSm6bElcNMMKJf4dcnhgv1x5m9LdicRam/Nu+KU4OjCF/lyt9vr5+oGJkQsopXP4j6YTYWrrvOvLuy25xRJQl4g7m0Q/eIlAYOIdnl3tKg9Jon+0KwmExTgQrrnDtgpZtExSLnFPlexoxz86GGbPGioQYe32aCj9gL2gjU5qselpeWk9kIzWBSRsk6Lc+sdW6xUJ/VoDpFFJocwjjdj09WCWNM9JMF8vtDzlFy6w/1X5hQVv/CnL/U8Q7X84f4Z6uc7bxlztJ6iHFYqo6ax3RVJwyB6wtjzxY1Vqa1cTjCd4/ilIznp+wi5QdLZVU4GfGrleW/0L/unVUZmMrUH9ARlU9twArs2mghOPuAToMWht6Fv1fLnIvK/zT6X07QCm5LvMVoR0cIgnDTWJMsMfwzgFmP/cK2WsI9uIUnUDhCxK3E+Vck3yLI5ZUdijGSgdNtRCn2YLU6aOum9MtV/c+DdoojjW5LRUPbIYx5yo38rxTAM6k0JnX1GkzFv4LbYxPNLCDToCuR8I1GMI5rnKravLPwmtAf19WQiRNfa/k6peRs7XEW/EzYO5ECB4m0Q044UzmzPKlt51RPDIr4NP5wF030wHaMWtlxrOKU3/0aJkcYwiBvV2pKMI2vuq3nTTajU/CageuwNP/ZQe+NEsWQaX0s61NdhSigojojw4zs9JOLIHRIwr5REDg1T6Os6/7W/UhAwsR81Pr5qTHx9+RJ1QGpZo0Qk2ETxyEKQJG6XHdhhDZt2mdCYkNTylbpxui+IUYb5K/HTtxn18ZVmTV7Ns7rqYwP69DQxARYvUdHScD7NNUjiRGBzdtzD6uo8hQTZSKf5NmGE9DaWY/xWTdcJLQRFo5jzlLRQLA/SsgYcXYY0dma4hOEhQwOA1faHYXDoSRe6sgYKydiihcaI/wtwA=,iv:hvm8ICrFjl1G4FQ7PT6PMWPawTNSt61b4ErqSza/b/c=,tag:945r9PMAjG2bItd/meQQGQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12vs3x7x0ne8ghx4js9dwetn29vvtrrelvcgup2reqmdhdeqwd9hqht25ex
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3ZEhZaHRFWXhZQU1HU0t0
            UEtLN0xJaGhjQy9xZThYQzhOMHBwdDJaV1RVCmxwNHBXbjZwem1CL3VJcXZoRTQ4
            dk9BZ01SSzBGUElZcW5PYlkrUzNYRDAKLS0tICs4NGxaU1U0SVRNYS9iZW5BM3V2
            cGRUTEJGNWRteENWUlFLbkI2Z0dwVTgK3MI/v3sJBIwQ3ruVR7YgJr7nXoc9hGcJ
            bNZfOOw8rU+hvKUqxrVWQS9SGalL65lK7znEvXhMr0zQwPl+CViDIA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-31T11:55:22Z"
    mac: ENC[AES256_GCM,data:OUOYVWOJGQw5y6DU7pIkVu+0ecofKmG/nDhyPdY56mPJlwzXmHt4bO/cOtR61E2t8cw2LwpDlIfebHQB5rN/qTngSsKDWPwvi/S08kwX5CQsSJ0tz8laQaFb+4l87nHaRF1AeQoDmhK/Nkm00g2pAsbW8PBe4gx2vhYDnnDMvqI=,iv:ciTev4fxJUp4ft5GQ5g9mHzoLgo3Hk5yO9sGVki6dEs=,tag:IAp42nwOn0Ss9kohCLkGRQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
