
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: tinkerers-bot
  namespace: tekton-pipelines
secrets:
  - name: regcred

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: tekton-pipelines
  name: tinkerers-bot
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tinkerers-bot
  namespace: tekton-pipelines
subjects:
- kind: ServiceAccount
  name: tinkerers-bot
  namespace: tekton-pipelines
roleRef:
  kind: ClusterRole
  name: tinkerers-bot
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: refresh-github-token-cronjob
  namespace: tekton-pipelines
spec:
  schedule: "20 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          imagePullSecrets:
          - name: regcred
          serviceAccountName: tinkerers-bot
          containers:
          - name: refresh-github-token
            env:
            - name: app_private_key
              valueFrom:
                secretKeyRef:
                  name: tinkerers-ci-pem
                  key: GITHUB_PEM
            - name: app_id
              value: "284804"
            - name: installation_id
              value: "33432247"
            image: quay.io/giantswarm/tinkerers-ci:latest
            command:
            - /bin/sh
            - -c
            - |
              BEARER_TOKEN=$(scripts/refresh-token.sh)

              #-------------------------
              # Update stored secret with new token 
              #-------------------------

              set +e
              kubectl delete secret -n tekton-pipelines tinkerers-ci-github-token 
              set -e

              kubectl -n tekton-pipelines create secret generic tinkerers-ci-github-token \
                --from-literal=GITHUB_TOKEN="${BEARER_TOKEN}"


              #-------------------------
              # basic-access-auth secret stored in flux-system namespace
              #-------------------------

              set +e
              kubectl delete secret -n flux-system basic-access-auth
              set -e

              kubectl -n flux-system create secret generic basic-access-auth \
              --from-literal=password="${BEARER_TOKEN}" \
              --from-literal=username=x-access-token

          restartPolicy: Never
