apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: github-pr-comment
  labels:
    app: tekton-resources
    app.kubernetes.io/name: tekton-resources
    app.kubernetes.io/instance: github-comment
    app.kubernetes.io/part-of: tekton-triggers
    application.giantswarm.io/team: team-tinkerers
  annotations:
    tekton.dev/tags: github, pull request, comment
spec:
  params:
  - name: URL
  - name: NUMBER
  - name: TITLE
  - name: BODY
  - name: GIT_REVISION
  - name: CLONE_URL
  - name: REPO_NAME
  - name: REPO_ORG
  - name: CHANGED_FILES
  - name: MERGEABLE_STATE
  - name: COMMENT
  - name: PREVIOUS_COMMENT
    default: ""
  - name: COMMENT_ID
    default: ""
  - name: COMMENT_URL
    default: ""
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: TaskRun
      metadata:
        generateName: github-pr-comment-filter-
      spec:
        taskSpec:
          steps:
            - image: ubuntu
              script: |
                #! /bin/bash
                # TODO: Filter out PRs based on ones we should handle and trigger the appropriate pipelines
