apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: github-pr-comment
  labels:
    app: tekton-resources
    app.kubernetes.io/name: tekton-resources
    app.kubernetes.io/instance: github-comment
    app.kubernetes.io/part-of: tekton-triggers
    application.giantswarm.io/team: team-tinkerers
  annotations:
    tekton.dev/tags: github, pull request, comment
spec:
  params:
  - name: URL
  - name: NUMBER
  - name: TITLE
  - name: BODY
  - name: GIT_REVISION
  - name: CLONE_URL
  - name: REPO_NAME
  - name: REPO_ORG
  - name: CHANGED_FILES
    default: ""
  - name: MERGEABLE_STATE
  - name: COMMENT
  - name: PREVIOUS_COMMENT
    default: ""
  - name: COMMENT_ID
    default: ""
  - name: COMMENT_URL
    default: ""
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: TaskRun
      metadata:
        generateName: github-pr-comment-filter-
      spec:
        serviceAccountName: trigger-filter
        params:
          - name: URL
            value: $(tt.params.URL)
          - name: NUMBER
            value: $(tt.params.NUMBER)
          - name: TITLE
            value: $(tt.params.TITLE)
          - name: BODY
            value: $(tt.params.BODY)
          - name: GIT_REVISION
            value: $(tt.params.GIT_REVISION)
          - name: CLONE_URL
            value: $(tt.params.CLONE_URL)
          - name: REPO_NAME
            value: $(tt.params.REPO_NAME)
          - name: REPO_ORG
            value: $(tt.params.REPO_ORG)
          - name: CHANGED_FILES
            value: $(tt.params.CHANGED_FILES)
          - name: MERGEABLE_STATE
            value: $(tt.params.MERGEABLE_STATE)
          - name: COMMENT
            value: $(tt.params.COMMENT)
          - name: PREVIOUS_COMMENT
            value: $(tt.params.PREVIOUS_COMMENT)
          - name: COMMENT_ID
            value: $(tt.params.COMMENT_ID)
          - name: COMMENT_URL
            value: $(tt.params.COMMENT_URL)
        taskSpec:
          description: |
            Checks a PR comment for trigger text and create new pipeline runs for each
          steps:
            - image: quay.io/giantswarm/pr-comment-filter:latest
