apiVersion: v1
kind: ServiceAccount
metadata:
  name: triggers-eventlistener
  labels:
    app: tekton-resources
    app.kubernetes.io/name: tekton-resources
    app.kubernetes.io/component: trigger-event-listener
    app.kubernetes.io/instance: github-pr
    app.kubernetes.io/part-of: tekton-triggers
    application.giantswarm.io/team: team-tinkerers

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: triggers-eventlistener-binding
  labels:
    app: tekton-resources
    app.kubernetes.io/name: tekton-resources
    app.kubernetes.io/component: trigger-event-listener
    app.kubernetes.io/instance: github-pr
    app.kubernetes.io/part-of: tekton-triggers
    application.giantswarm.io/team: team-tinkerers
subjects:
- kind: ServiceAccount
  name: triggers-eventlistener
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-roles

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: triggers-eventlistener-clusterbinding
  labels:
    app: tekton-resources
    app.kubernetes.io/name: tekton-resources
    app.kubernetes.io/component: trigger-event-listener
    app.kubernetes.io/instance: github-pr
    app.kubernetes.io/part-of: tekton-triggers
    application.giantswarm.io/team: team-tinkerers
subjects:
- kind: ServiceAccount
  name: triggers-eventlistener
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-clusterroles

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: trigger-filter
  labels:
    app: tekton-resources
    app.kubernetes.io/name: tekton-resources
    app.kubernetes.io/component: trigger-filter
    app.kubernetes.io/part-of: tekton-triggers
    application.giantswarm.io/team: team-tinkerers

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: trigger-filter
  labels:
    app: tekton-resources
    app.kubernetes.io/name: tekton-resources
    app.kubernetes.io/component: trigger-filter
    app.kubernetes.io/part-of: tekton-triggers
    application.giantswarm.io/team: team-tinkerers
rules:
  # Check for pipelines existing
  - apiGroups: ["tekton.dev"]
    resources: ["pipelines"]
    verbs: ["get", "list"]
  # Create the new pipeline runs from triggers
  - apiGroups: ["tekton.dev"]
    resources: ["pipelineruns"]
    verbs: ["get", "list", "create"]
  # Check for validity of ServiceAccount and Namespaces referenced in triggers
  - apiGroups: [""]
    resources: ["serviceaccounts", "namespaces"]
    verbs: ["get", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: trigger-filter
  labels:
    app: tekton-resources
    app.kubernetes.io/name: tekton-resources
    app.kubernetes.io/component: trigger-filter
    app.kubernetes.io/part-of: tekton-triggers
    application.giantswarm.io/team: team-tinkerers
subjects:
- kind: ServiceAccount
  name: trigger-filter
  namespace: tekton-pipelines
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: trigger-filter
