apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone
  labels:
    application.giantswarm.io/team: team-tinkerers
  annotations:
    tekton.dev/tags: git, github
    tekton.dev/displayName: "clone a git repository"
spec:
  description: Clones a git repository into the provided workspace

  workspaces:
  - name: output
    description: The git repo will be cloned onto the volume backing this Workspace.

  params:
  # Required
  - name: URL
    type: string
    description: Repository URL to clone from.

  # Optional
  - name: REVISION
    type: string
    description: Revision to checkout. (branch, tag, sha, ref, etc...)
    default: "HEAD"

  steps:
    - name: clone
      image: alpine/git:latest
      env:
      - name: URL
        value: $(params.URL)
      - name: REVISION
        value: $(params.REVISION)
      - name: GITHUB_TOKEN
        valueFrom:
          secretKeyRef:
              name: tinkerers-ci-github-token
              key: GITHUB_TOKEN
      script: |
        #!/usr/bin/env sh
        set -eu
        git clone "https://oauth2:${GITHUB_TOKEN}@${URL}" $(workspaces.output.path)/

        cd $(workspaces.output.path)/

        git fetch

        git checkout ${REVISION}
