apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- pairs:
    application.giantswarm.io/team: team-tinkerers
  includeTemplates: true

resources:
# repo: tektoncd/pipeline
- https://github.com/tektoncd/pipeline/releases/download/v0.45.0/release.yaml
# repo: tektoncd/triggers
- https://github.com/tektoncd/triggers/releases/download/v0.23.0/release.yaml
# repo: tektoncd/triggers
- https://github.com/tektoncd/triggers/releases/download/v0.23.0/interceptors.yaml
# repo: tektoncd/dashboard
- https://github.com/tektoncd/dashboard/releases/download/v0.33.0/release.yaml
- resources/oauth2-proxy.yaml
- resources/dashboard-ingress.yaml
- resources/dashboard-extensions-base.yaml
- resources/dashboard-extensions-cronjobs.yaml
- resources/dashboard-extensions-jobs.yaml
- resources/psps.yaml
- resources/secrets.yaml

patchesStrategicMerge:
- patches/tekton-pipelines.yaml

patchesJson6902:
- patch: |-
    - op: remove
      path: "/metadata/labels/pod-security.kubernetes.io~1enforce"
  target:
    kind: Namespace
    name: tekton-pipelines
- patch: |-
    - op: remove
      path: "/metadata/labels/pod-security.kubernetes.io~1enforce"
  target:
    kind: Namespace
    name: tekton-pipelines-resolvers
